//! Raw FFI bindings to `libopenconnect`.
//!
//! Generated by `bindgen` at build time. See `build.rs`.
//! Consumers should prefer the safe wrapper in the `gp-tunnel` crate.
//!
//! On Windows, set `OPENCONNECT_DIR` to the libopenconnect install prefix.
//! On Unix, `pkg-config` finds it automatically. When the library is not
//! available, the crate emits empty bindings and `gp-tunnel` falls back
//! to a stub.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

#[cfg(any(unix, windows))]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// --- Progress callback trampoline (csrc/progress_shim.c) ---
//
// libopenconnect's progress callback is variadic (printf-style). Rust on
// stable can't define variadic C functions, so we route through a small C
// trampoline that formats the message and calls a plain Rust sink.

#[cfg(any(unix, windows))]
extern "C" {
    /// Variadic trampoline exported by `csrc/progress_shim.c`. Pass its
    /// address as the `progress` argument to `openconnect_vpninfo_new`.
    pub fn openprotect_progress_trampoline(
        privdata: *mut ::std::os::raw::c_void,
        level: ::std::os::raw::c_int,
        fmt: *const ::std::os::raw::c_char,
        ...
    );
}

/// Non-variadic Rust sink that the C trampoline forwards pre-formatted
/// progress messages to. Called from C, so `extern "C"` and `#[no_mangle]`.
///
/// Routes messages to `tracing` at a level inferred from libopenconnect's
/// `PRG_*` constants.
///
/// # Safety
/// `msg` must be a NUL-terminated C string or NULL. Callers (i.e. the C
/// trampoline in `csrc/progress_shim.c`) always pass a valid pointer from
/// `vsnprintf`. `privdata` is unused.
#[cfg(any(unix, windows))]
#[no_mangle]
pub unsafe extern "C" fn openprotect_progress_sink(
    _privdata: *mut ::std::os::raw::c_void,
    level: ::std::os::raw::c_int,
    msg: *const ::std::os::raw::c_char,
) {
    if msg.is_null() {
        return;
    }
    let cstr = unsafe { std::ffi::CStr::from_ptr(msg) };
    let s = cstr.to_string_lossy();
    // PRG_ERR = 0, PRG_INFO = 1, PRG_DEBUG = 2, PRG_TRACE = 3.
    //
    // libopenconnect emits a handful of informational messages at
    // PRG_ERR — notably `gpst.c::calculate_mtu` warning "No MTU
    // received. Calculated ... for ESP tunnel" when the server does
    // not push an MTU in getconfig, which is routine for Prisma
    // Access and not an error at all. Downgrade the known-benign
    // strings to `warn` so our own ERROR log is reserved for
    // things that actually break the tunnel.
    match level {
        0 => {
            if is_benign_error(&s) {
                tracing::warn!(target: "openconnect", "{}", s);
            } else {
                tracing::error!(target: "openconnect", "{}", s);
            }
        }
        1 => tracing::info!(target: "openconnect", "{}", s),
        2 => tracing::debug!(target: "openconnect", "{}", s),
        _ => tracing::trace!(target: "openconnect", "{}", s),
    }
}

/// Known `PRG_ERR`-level messages from libopenconnect that are not
/// actually errors — callers should see them as warnings. Keep the
/// list narrow and well-commented; anything not on it stays at
/// `error` level so we do not swallow real failures.
fn is_benign_error(msg: &str) -> bool {
    // `gpst.c::calculate_mtu`: server did not push an MTU in
    // getconfig.esp. libopenconnect calculates 1500 - overhead and
    // the tunnel works fine. Observed on every UNSW Prisma Access
    // session, and present verbatim in yuezk's logs too. The full
    // upstream string is `"No MTU received. Calculated N for ESP
    // tunnel"`; match as a prefix (not a bare `contains`) so a
    // hypothetical future message like `"Gateway rejected config
    // because No MTU received for IPv6"` would NOT be silently
    // downgraded.
    if msg.starts_with("No MTU received") {
        return true;
    }

    // `tun-win32.c`: libopenconnect logs the freshly-created Wintun
    // adapter at PRG_ERR (e.g., `Using Wintun device
    // 'ra.vpn.example.com', index 60`). It's purely informational —
    // upstream uses `vpn_progress(PRG_ERR, ...)` because that's the
    // only level always emitted at default verbosity. Match as a
    // prefix so the closely-named real error `Could not create
    // Wintun adapter` (also from tun-win32.c) still surfaces as
    // ERROR.
    if msg.starts_with("Using Wintun device") {
        return true;
    }

    // `tun-win32.c`: blanket "Wintun is experimental" warning that
    // upstream emits every time it brings up the adapter. We've been
    // shipping Wintun in production for months — there's nothing
    // actionable about this line and routing it through `tracing::
    // error!` makes the connect log look broken when it isn't.
    if msg.starts_with("WARNING: Support for Wintun is experimental") {
        return true;
    }

    // `gpst.c`: libopenconnect logs a multi-line "WARNING: Server
    // asked us to submit HIP report ... However, running the HIP
    // report submission script on this platform is not yet
    // implemented" whenever it sees `hipreportcheck.esp` say a
    // report is needed AND we did not register a csd wrapper (we
    // can't on Windows — see `gp-tunnel::setup_csd`). This is
    // libopenconnect telling us *it* can't submit HIP, but our
    // Rust-side `submit_hip_from_rust` covers exactly that case
    // and posts the report on its own. Downgrade the upstream
    // warning so the actual `HIP: report submitted successfully`
    // log isn't drowned out by a fake-looking error.
    if msg.starts_with("WARNING: Server asked us to submit HIP report") {
        return true;
    }

    false
}
